"""
PDF service — converts tutorial chapters to a formatted PDF document.

Uses fpdf2 for pure-Python PDF generation with no system dependencies.
"""

import re
from pathlib import Path

from fpdf import FPDF

from utils.logger import get_logger

logger = get_logger(__name__)


class _TutorialPDF(FPDF):
    """Custom PDF class with header/footer for the tutorial document."""

    def __init__(self, repo_name: str) -> None:
        super().__init__()
        self.repo_name = repo_name

    def header(self) -> None:
        """Render page header with repo name."""
        self.set_font("Helvetica", "I", 9)
        self.set_text_color(130, 130, 130)
        self.cell(0, 10, f"{self.repo_name} — AI Tutorial", align="R")
        self.ln(5)

    def footer(self) -> None:
        """Render page footer with page number."""
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(130, 130, 130)
        self.cell(0, 10, f"Page {self.page_no()}/{{nb}}", align="C")


def _render_markdown_line(pdf: FPDF, line: str) -> None:
    """Render a single markdown line with basic formatting.

    Supports: headings (# ## ### ####), bold (**text**), inline code (`code`),
    bullet points (- item), and plain text.
    """
    stripped = line.strip()

    if not stripped:
        pdf.ln(3)
        return

    # Headings
    if stripped.startswith("#### "):
        pdf.set_font("Helvetica", "B", 11)
        pdf.set_text_color(40, 40, 40)
        pdf.multi_cell(0, 7, stripped[5:])
        pdf.ln(2)
    elif stripped.startswith("### "):
        pdf.set_font("Helvetica", "B", 12)
        pdf.set_text_color(40, 40, 40)
        pdf.multi_cell(0, 7, stripped[4:])
        pdf.ln(2)
    elif stripped.startswith("## "):
        pdf.set_font("Helvetica", "B", 14)
        pdf.set_text_color(30, 30, 30)
        pdf.multi_cell(0, 8, stripped[3:])
        pdf.ln(3)
    elif stripped.startswith("# "):
        pdf.set_font("Helvetica", "B", 16)
        pdf.set_text_color(20, 20, 20)
        pdf.multi_cell(0, 9, stripped[2:])
        pdf.ln(4)
    elif stripped.startswith("- ") or stripped.startswith("* "):
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(50, 50, 50)
        pdf.cell(8)  # indent
        pdf.multi_cell(0, 6, f"  •  {stripped[2:]}")
    elif stripped.startswith("> "):
        # Blockquote
        pdf.set_font("Helvetica", "I", 10)
        pdf.set_text_color(100, 100, 100)
        pdf.cell(10)  # indent
        pdf.multi_cell(0, 6, stripped[2:])
        pdf.set_text_color(50, 50, 50)
    else:
        # Plain paragraph text — strip markdown bold/code markers
        clean = re.sub(r"\*\*(.*?)\*\*", r"\1", stripped)
        clean = re.sub(r"`(.*?)`", r"\1", clean)
        clean = re.sub(r"\[(.*?)\]\(.*?\)", r"\1", clean)  # links
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(50, 50, 50)
        pdf.multi_cell(0, 6, clean)


def create_tutorial_pdf(
    chapters: list,
    repo_name: str = "Repository",
) -> bytes:
    """Generate a PDF document from tutorial chapters.

    Args:
        chapters: List of Chapter objects with title, content, filename.
        repo_name: Repository name for the title page.

    Returns:
        PDF file contents as bytes.
    """
    if not chapters:
        logger.warning("No chapters provided for PDF generation")
        return b""

    pdf = _TutorialPDF(repo_name)
    pdf.alias_nb_pages()
    pdf.set_auto_page_break(auto=True, margin=20)

    # --- Title page ---
    pdf.add_page()
    pdf.ln(60)
    pdf.set_font("Helvetica", "B", 28)
    pdf.set_text_color(30, 30, 30)
    pdf.cell(0, 15, repo_name, align="C")
    pdf.ln(12)
    pdf.set_font("Helvetica", "", 16)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 10, "AI-Generated Tutorial", align="C")
    pdf.ln(8)
    pdf.set_font("Helvetica", "I", 11)
    pdf.cell(0, 10, f"{len(chapters)} Chapters", align="C")
    pdf.ln(20)
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(150, 150, 150)
    pdf.cell(0, 10, "Generated by AI Codebase Assistant", align="C")

    # --- Table of Contents ---
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(30, 30, 30)
    pdf.cell(0, 12, "Table of Contents")
    pdf.ln(10)

    for i, chapter in enumerate(chapters, 1):
        pdf.set_font("Helvetica", "", 11)
        pdf.set_text_color(50, 50, 120)
        pdf.cell(0, 8, f"{i}. {chapter.title}")
        pdf.ln(5)

    # --- Chapters ---
    for i, chapter in enumerate(chapters, 1):
        pdf.add_page()

        # Chapter title
        pdf.set_font("Helvetica", "B", 20)
        pdf.set_text_color(20, 20, 20)
        pdf.multi_cell(0, 11, f"Chapter {i}: {chapter.title}")
        pdf.ln(6)

        # Render chapter content line by line
        in_code_block = False
        for line in chapter.content.split("\n"):
            # Skip code fence markers, render code content in monospace
            if line.strip().startswith("```"):
                in_code_block = not in_code_block
                if in_code_block:
                    pdf.ln(2)
                    pdf.set_fill_color(240, 240, 240)
                else:
                    pdf.ln(2)
                continue

            if in_code_block:
                pdf.set_font("Courier", "", 8)
                pdf.set_text_color(60, 60, 60)
                # Truncate very long code lines
                display_line = line[:120] if len(line) > 120 else line
                pdf.cell(0, 5, f"  {display_line}", new_x="LMARGIN", new_y="NEXT")
            else:
                _render_markdown_line(pdf, line)

    pdf_bytes = pdf.output()

    logger.info(
        "Generated PDF: %d chapters, %d bytes",
        len(chapters),
        len(pdf_bytes),
    )

    return pdf_bytes
